version: '2'

services:
  hist_report:
    build: report
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.histproj.rule=Host(`hist-175.johncunniff.dev`)"
      - "traefik.http.routers.histproj.entrypoints=https"
      - "traefik.http.routers.histproj.tls.certresolver=tls"
      - "traefik.http.services.histproj.loadbalancer.server.port=3000"
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external:
      name: traefik-proxy
