version: '3'

services:
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379

  # bloom:
  #   image: redislabs/rebloom:latest
  #   ports:
  #     - 6378:6379

  zero1:
    image: dgraph/dgraph:latest
    restart: on-failure
    volumes:
      - ./.dgraph/z1:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    command: dgraph zero --my=zero1:5080 --replicas 3

  zero2:
    image: dgraph/dgraph:latest
    restart: on-failure
    volumes:
      - ./.dgraph/z2:/dgraph
    ports:
      - 5081:5081
      - 6081:6081
    command: dgraph zero -o 1 --my=zero2:5081 --replicas 3 --peer zero1:5080

  zero3:
    image: dgraph/dgraph:latest
    restart: on-failure
    volumes:
      - ./.dgraph/z3:/dgraph
    ports:
      - 5082:5082
      - 6082:6082
    command: dgraph zero -o 2 --my=zero3:5082 --replicas 3 --peer zero1:5080

  alpha1:
    image: dgraph/dgraph:latest
    restart: on-failure
    volumes:
      - ./.dgraph/a1:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    command: dgraph alpha --my=alpha1:7080 --zero=zero1:5080,zero2:5081,zero3:5082 --security whitelist=0.0.0.0/0

  alpha2:
    image: dgraph/dgraph:latest
    restart: on-failure
    volumes:
      - ./.dgraph/a2:/dgraph
    ports:
      - 8081:8081
      - 9081:9081
    command: dgraph alpha --my=alpha2:7081 --zero=zero1:5080,zero2:5081,zero3:5082 -o 1 --security whitelist=0.0.0.0/0

  alpha3:
    image: dgraph/dgraph:latest
    restart: on-failure
    volumes:
      - ./.dgraph/a3:/dgraph
    ports:
      - 8082:8082
      - 9082:9082
    command: dgraph alpha --my=alpha3:7082 --zero=zero1:5080,zero2:5081,zero3:5082 -o 2 --security whitelist=0.0.0.0/0

  alpha4:
    image: dgraph/dgraph:latest
    restart: on-failure
    volumes:
      - ./.dgraph/a4:/dgraph
    ports:
      - 8083:8083
      - 9083:9083
    command: dgraph alpha --my=alpha4:7083 --zero=zero1:5080,zero2:5081,zero3:5082 -o 3 --security whitelist=0.0.0.0/0

  alpha5:
    image: dgraph/dgraph:latest
    restart: on-failure
    volumes:
      - ./.dgraph/a5:/dgraph
    ports:
      - 8084:8084
      - 9084:9084
    command: dgraph alpha --my=alpha5:7084 --zero=zero1:5080,zero2:5081,zero3:5082 -o 4 --security whitelist=0.0.0.0/0

  alpha6:
    image: dgraph/dgraph:latest
    restart: on-failure
    volumes:
      - ./.dgraph/a6:/dgraph
    ports:
      - 8085:8085
      - 9085:9085
    command: dgraph alpha --my=alpha6:7085 --zero=zero1:5080,zero2:5081,zero3:5082 -o 5 --security whitelist=0.0.0.0/0

  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
